export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST'

export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'

export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_SUCCESS'

export const FETCH_USERS_POST_REQUEST = 'FETCH_USERS_POST_REQUEST'

export const FETCH_USERS_POST_SUCCESS = 'FETCH_USERS_POST_SUCCESS'

export const FETCH_USERS_POST_FAILURE = 'FETCH_USERS_POST_FAILURE'